version: '3.8'
services:
  relay:
    image: dashford/relay:latest
    container_name: relay
    env_file: .env
    volumes:
      - type: bind
        source: ./config/config.yaml
        target: /usr/src/app/config/config.yaml